org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=false

mod_id=kivotos_armorer
mod_name=Kivotos Armorer
mod_group=com.kivotos.armorer
mod_version=1.0.0
mod_license=All Rights Reserved
mod_authors=World of Kivotos

mc_version=1.20.1
forge_version=47.3.0
forge_full_version=1.20.1-47.3.0
parchment_minecraft=1.20.1
parchment_version=2023.09.03
