pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org/' }
    }
    plugins {
        id 'net.minecraftforge.gradle' version '[6.0,6.2)'
        id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    }
}

rootProject.name = 'KivotosArmorer'
